config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'visitors#index'

  get 'saved_searches', to: 'visitors#saved_searches'
  get 'listings', to: 'listings#index'
  post '/listings/refresh', to: 'listings#refresh', as: 'run_searches'
  post '/listings/:id/decide/:action', to: 'listings#decide', as: 'decide_on_listing'
  get '/listings/:id/compare', to: 'listings#compare', as: 'compare_site_listings'

  resources :listings do
    resources :notes
  end

  resources :searches, only: [:index] do
    resources :listings
  end
end

app/models/listing.rb
# Ideally each business for sale has a single listing, delegating to separate SiteListings
# as needed when the same business is listed on multiple sites.
class Listing < ActiveRecord::Base
  # TODO: if we ever really add multiple users, convert this to
  # has_many :through, and move the state machine, etc. to the join model.
  belongs_to :user
  has_many :site_listings, dependent: :destroy
  has_many :notes, dependent: :destroy
  has_and_belongs_to_many :saved_searches

  scope :undecided, -> { where(status: ['unseen', 'maybe']) }
  scope :yep, -> { where(status: 'yep') }
  scope :nope, -> { where(status: 'nope') }

  state_machine :status, initial: :unseen do
    state :unseen
    state :nope
    state :maybe
    state :yep

    event :nope do
      transition all => :nope
    end

    event :maybe do
      transition all => :maybe
    end

    event :yep do
      transition all => :yep
    end

  end

  def primary_site_listing
    site_listings.first
  end

  def self.delegate_first_not_nil(*fields)
    fields.each do |field|
      define_method field do
        site_listings.detect {|l| l.send(field) }.try(field)
      end
    end
  end

  def self.delegate_lowest(*fields)
    fields.each do |field|
      define_method field do
        site_listings.map {|l| l.send(field) }.compact.min
      end
    end
  end

  delegate :title, :description, :city, :state, to: :primary_site_listing

  delegate_first_not_nil :reason_selling, :seller_financing, :employees, :established

  delegate_lowest :price, :cashflow, :revenue, :ffe, :inventory, :real_estate

  def self.import(result, site:, saved_search:)
    return unless sl = SiteListing.handle_new(result, site: site, owner: saved_search.user)
    dups    = sl.duplicates_on_other_networks(saved_search)
    listing = sl.listing || dups.detect(&:listing).try(:listing) || saved_search.user.listings.new
    listing.saved_searches << saved_search unless listing.saved_searches.include?(saved_search)

    dups.each do |dup|
      dup.update_attributes(listing: listing)
    end

    sl.update_attributes!(listing: listing)

    return listing
  end

  def repayment_projection
    RepaymentProjection.new(self)
  end

  def multiple
    return unless cashflow && price
    (price.to_f / cashflow).round(2)
  end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  before_action :get_listings, only: [:index]
  before_action :get_listing,  only: [:decide, :compare]

  def index
  end

  def refresh
    # TODO: this should be scoped to the specific search group
    current_user.saved_searches.each {|s| s.update! }

    flash[:info] = "Started job search agent (refresh in a few minutes to see any updates)"

    redirect_to action: :index
  end

  def decide
    render(nothing: true, status: 500) and return unless %w(yep nope maybe).include?(params[:decision])

    @listing.send( params[:decision] )
    render(nothing: true, status: 200)
  end

  def compare
    @site_listings = @listing.site_listings
    render layout: 'modal'
  end

  private

  def base
    get_search || current_user
  end

  def get_listing
    @listing = base.listings.find(params[:id])
  end

  def get_listings
    scope = %w(yep nope).include?(params[:status]) ? params[:status] : 'undecided'
    @listings = base.listings.send(scope).includes(:site_listings)
  end

  def get_search
    if params[:search_id]
      @search = current_user.search_groups.find(params[:search_id])
    end
  end

end

app/helpers/listing_helper.rb
module ListingHelper

  def listing_status(l)
    label, text = case l.status
    when 'unseen' then ['warning', 'New']
    when 'maybe'  then ['primary', 'Maybe']
    when 'nope'   then ['danger',  'Nope']
    when 'yep'    then ['success', 'Yep']
    else               ['default', "? #{l.status} ?"]
    end

    content_tag :span, text, class: "label label-#{label}"
  end

  def format_description(desc)
    return unless desc
    desc
      .gsub(/\[([\w\s\/-]+)\]:/, '<h6>\1</h6>')
      .gsub(/\n\n\n/, '<br>')
      .gsub(/\r\n/, '<br>')
  end

  def listing_note(listing, note)
    title = note.created_at.strftime("Noted at %k:%M on %b %e (%Z)")
    close = link_to "&times;".html_safe, listing_note_path(listing, note), class: 'close note-destroy',
      remote: true,
      method: :delete,
      data: {confirm: "Are you sure?", disable_with: 'Confirming...'}

    render 'shared/panel', body: note.body, type: :info, title: title, close: close
  end

  def compare_site_listings(fields)
    rows = fields.map do |field|
      {
        title: field.titleize,
        values: @site_listings.map do |sl|
          val = sl.send(field)
          block_given? ? yield(val) : val
        end
      }
    end

    render partial: 'comparison_rows', locals: {rows: rows}
  end

  def filter_label
    case params[:status]
    when 'yep'  then 'accepted'
    when 'nope' then 'rejected'
    else 'all'
    end
  end

end

app/views/listings/_comparison_rows.html.haml
- rows.each do |row|
  %tr
    %th= row[:title]
    - row[:values].each do |v|
      %td= v

app/views/listings/_listings_header.html.haml
%p
  Showing #{filter_label}
  - if @search
    listings for your #{link_to @search.name, searches_path(anchor: @search.id)} search group.
  - else
    listings.

  %em
    #{link_to 'Refresh', run_searches_path, method: :post}.

app/views/listings/compare.html.haml
- @modal_title = "Compare Site Listings"
- @modal_size = :large

%table.table
  %thead
    %tr
      %th &nbsp;
      - @site_listings.each do |sl|
        %th= sl.site.name
  %tbody
    = compare_site_listings %w(title city state)
    = compare_site_listings(%w(price cashflow revenue ffe inventory real_estate)) { |v| dollars(v) }
    = compare_site_listings %w(inventory_included real_estate_included employees established reason_selling seller_financing created_at updated_at description)
    = compare_site_listings(%w(link)) { |v| link_to v, v, target: '_blank' }

app/views/listings/index.html.haml
%h3 Listings


.row
  .col-sm-6
    = render partial: 'listings_header'

  .col-sm-6
    %p
      %strong Showing:
      = link_to_unless_current 'Yep', listings_path(status: :yep)
      |
      = link_to_unless_current 'Nope', listings_path(status: :nope)
      |
      = link_to_unless params[:status].blank? || params[:status] == 'maybe', 'Undecided', listings_path(status: :maybe)

%hr
- if @listings.length.zero?
  %h2.text-center
    Nothing to show
    %small
      = link_to 'Refresh results?', run_searches_path, method: :post
- else
  %table#listings-table.table.table-striped.table-hover
    %thead
      %tr
        %th
        %th Location
        %th Price
        %th Cashflow
        %th Projected (post tax)
        %th Multiple
        %th Status
        %th Title
        %th Body

    %tbody
      - @listings.each do |listing|
        %tr.listing
          %td.clickable
          %td.clickable= [listing.state, listing.city].compact.join(', ')
          %td.clickable= dollars listing.price
          %td.clickable= dollars listing.cashflow
          %td.clickable
            - if cash = listing.repayment_projection.cashflow_after_repayment
              .pull-left{class: cash > 0 ? 'text-muted' : 'text-danger'}= dollars cash
            - if cash = listing.repayment_projection.cashflow_post_tax_and_repayment
              .pull-right{class: cash > 0 ? 'text-muted' : 'text-danger'} (#{dollars cash})
          %td.clickable= listing.multiple

          %td.status
            = listing_status listing
            .buttons
              - unless params[:status] == 'yep'
                = link_to decide_on_listing_path(listing, decision: :yep), class: 'btn btn-xs btn-success', remote: true, method: :post do
                  %span.glyphicon.glyphicon-thumbs-up
              = link_to decide_on_listing_path(listing, decision: :maybe), class: 'btn btn-xs btn-primary', remote: true, method: :post do
                %span.glyphicon.glyphicon-question-sign
              - unless params[:status] == 'nope'
                = link_to decide_on_listing_path(listing, decision: :nope), class: 'btn btn-xs btn-danger', remote: true, method: :post do
                  %span.glyphicon.glyphicon-thumbs-down

          %td.clickable.title
            .normal
              = listing.title
              .badge{class: (sl_count = listing.site_listings.size) > 1 ? '' : 'hidden'} #{sl_count} sites
              .badge{class: (note_count = listing.notes.count) > 0 ? '' : 'hidden'}
                Notes:
                %span.note_count= note_count
            .detail
              = form_for :note, url: listing_notes_path(listing), method: :post, remote: true, html: {class: 'form note-form'} do |f|
                = f.text_field :body, class: 'form-control', placeholder: 'Add note...'
                = f.submit 'Save', class: 'btn btn-primary'

          %td.details
            .well.clearfix
              .pull-right
                %strong= pluralize sl_count, 'Site:', 'Sites:'
                =raw listing.site_listings.map { |sl| link_to sl.site.name, sl.link, target: '_blank' }.join(' | ')
                ||
                = link_to 'Details', compare_site_listings_path(listing), remote: true, class: 'remote-modal'
              - if (links = listing.site_listings.map(&:business_url).compact.uniq).present?
                ||
                = links.map {|l| link_to 'Business Link', l, target: '_blank' }.join(' | ')
              .pull-left
                First seen
                %strong #{time_ago_in_words listing.created_at} ago


            .notes
              - listing.notes.reverse.each do |note|
                = listing_note listing, note

            .well=raw format_description listing.description


%hr

%h3 Caveats:
%ul
  %li Projections may be invalid for listings with e.g. real estate or inventory not included in purchase price.
  %li Listings attempt to properly group duplicates across different networks, but may fail (especially if numbers change between postings).
  %li If a listing is reposted on the same network, that'll count as a new/separate post (although depending on if numbers were changed, if it's on a second network as well the deduplication process there may bundle it as well).