config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'visitors#index'

  get 'saved_searches', to: 'visitors#saved_searches'
  get 'listings', to: 'listings#index'
  post '/listings/refresh', to: 'listings#refresh', as: 'run_searches'
  post '/listings/:id/decide/:action', to: 'listings#decide', as: 'decide_on_listing'
  get '/listings/:id/compare', to: 'listings#compare', as: 'compare_site_listings'

  resources :listings do
    resources :notes
  end

  resources :searches, only: [:index] do
    resources :listings
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def index
    @searches = current_user.search_groups
  end

end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/index.html.haml
%h3 Searches

%p For now, manage changes to saved searches directly in the database.

- @searches.each do |group|
  .well
    %h3{id: group.id}= link_to group.name, search_listings_path(group)

    %table.table.table-hover
      %tr
        %th Name
        %th Priority
        %th Min Cashflow
        %th State
        %th City
        %th Keyword
        %th Listings
        %th Links (only some sources can filter on-site)

      - group.saved_searches.each do |search|
        %tr
          %td= search.name
          %td= search.priority
          %td= dollars search.min_cashflow
          %td= search.state
          %td= search.city
          %td= search.keyword || 'n/a'
          %td= search.listings.count
          %td
            |
            - search.sites.each do |site|
              - src = site.adapter( search )
              - if src.respond_to?(:url_for_page)
                = link_to site.name, src.url_for_page(1), target: '_blank'
              - else
                #{site.name} (API Only)
              |